create table funcionario (
       id bigint generated by default as identity,
        matricula varchar(20) not null,
        nome varchar(150) not null,
        primary key (id)
    );

    
    alter table funcionario 
       add constraint UK_3uda6owswwy94ktwvq5uhifx1 unique (matricula);